In [2]:
import numpy as np

In [ ]:
# как создать вектор?


In [4]:
# как одномерный массив numpy
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [6]:
# преобразовать из списка list
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [8]:
# нулевой вектор
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [9]:
# вектор из единиц
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# массив чисел по порядку
np.arange(10,50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
# случайный вектор
np.random.randint(-4, 2, 10) # dim=10, случаные целые числа от -4 до 2

array([-4,  1,  1, -3, -2, -2,  1,  1,  0, -1])

In [12]:
# преобразовать из pandas Series
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n',s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [13]:
x = s.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [14]:
# преобразовать из pandas Data Frame
d = {'$$': [65, 70, 120, 35], '2.Area': [50, 52, 80, 33],'3.Rooms':[3,2,1,1], 
     '4.Floor':[5,12,10,3], '5.Demo':[8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n',df)

Data Frame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [15]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [29]:
x=A[1] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [18]:
y=A[:,0] # первый столбец матрицы А
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [19]:
# индексация векторов - поиск нужной координаты
print('$$ of 3 apartment:',y[2]) # третья координата

$$ of 3 apartment: 120


In [30]:
# размерность вектора
print('Number of apartments = dim(x):', len(x))

Number of apartments = dim(x): 5


In [31]:
# сумма векторов и умножение на число
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:',a+b)
print('2a:',2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [32]:
# сумма списков и умножение на число не является векторной операцией!
a_list=[1,2,3]
b_list=[6,7,8]
print('a+b:',a_list+b_list)
print('2a:',2*a_list)

a+b: [1, 2, 3, 6, 7, 8]
2a: [1, 2, 3, 1, 2, 3]


In [33]:
# линейная комбинация с коэффициентами 2, 2, 3
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:',d)

linear combination: [17 18 25]


In [34]:
# скалярное произведение

s=np.dot(a,b)
print('scalar product:',s)

# покоординатное умножение
print('coordinate product:',a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [35]:
# скалярное произведение - еще один способ
s1=a@b
print('scalar product:',s1)

scalar product: 44


In [36]:
# длина вектора
l=np.linalg.norm(a)
print('length of a:',l)

length of a: 3.7416573867739413


In [37]:
# нормировка
a_norm=a/np.linalg.norm(a)
print('a_norm:',a_norm)
print('length of a_norm:',np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [38]:
#пропорциональность и ортогональность
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [ ]:
#пропорциональность и ортогональность
print("(a,b):",np.dot(a,b))
print("(a,c):",np.dot(a,c))
print("(b,c):",np.dot(b,c))

In [ ]:
# попарная ортогональность - да
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

In [ ]:
# попарная ортогональность - да
print('(a,b):',np.dot(a,b))
print('(b,c):',np.dot(a,b))
print('(a,c):',np.dot(a,c))

In [ ]:
# попарная ортогональность - нет
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('с1:',c1)

In [ ]:
# попарная ортогональность - нет
print('(a,b):',a@b)
print('(b,c1):',b@c1)
print('(a,c1):',a@c1)